config/routes.rb
ConnotiveCartoon::Application.routes.draw do

  get "books/index"
  match "books/show/:id" => 'books#show', :as => :books_show, :via => :get
  get "/about", to: 'about#index'

  get "cartoons/:nav/page/:page", to: 'cartoons#index'
  
  match "cartoons/check/list" => "cartoons#check_list", :as => :check_cartoons, :via => :get
  match "cartoons/check/:id" => "cartoons#check", :as => :check_cartoon, :via => :get
  match "user/:username" => "user#show", :as => :show_user, :via => :get
  get "user/edit"
  get "user/update"

  post "comments/create"
  post "comments/add_book_comment"

  devise_for :users

  root :to => 'cartoons#index'
  get "cartoons/index"
  match "cartoons/:nav/show/:id" => "cartoons#show", :as => :show_cartoons, :via => :get
  match "cartoons/download/:id" => "cartoons#download", :as => :download_cartoon, :via => :get
  get "/download/apk", to: "cartoons#download_apk", :as => :download_apk

  namespace :admin do 
    get "system/index"
    get "system/show_upload_apk"
    post "system/upload_apk"
    get "system/edit_apk/:id", to: 'system#edit_apk', :as => :system_edit_apk
    put "system/update_apk/:id", to: 'system#update_apk', :as => :system_update_apk

    get "categories/list"
    get "categories/new"
    post "categories/create"
    get "categories/edit/:id", to: "categories#edit", :as => "categories_edit"
    put "categories/update/:id", to: "categories#update", :as => "categories_update"
    delete "categories/destroy/:id", to: "categories#destroy", :as => "categories_destroy"

    get "cartoons/index"
    get "cartoons/list"
    get "cartoons/new"
    get "cartoons/show"
    get "cartoons/create"
    get "cartoons/edit"
    get "cartoons/update"
    match "cartoons/destroy/:id" => "cartoons#destroy", :as => :destroy_cartoon, :via => :delete
    post "cartoons/import"
    post "cartoons/get_cartoons_list"

    get "scrap_sources/list"
    get "scrap_sources/new"
    match "scrap_sources/show/:id" => "scrap_sources#show", :as => :show_scrap_source, :via => :get
    match "scrap_sources/create" => "scrap_sources#create", :as => :create_scrap_source, :via => :post
    match "scrap_sources/edit/:id" => "scrap_sources#edit", :as => :edit_scrap_source, :via => :get
    match "scrap_sources/update/:id" => "scrap_sources#update", :as => :update_scrap_source, :via => :put
    match "scrap_sources/destroy/:id" => "scrap_sources#destroy", :as => :destroy_scrap_source, :via => :delete
  
    get "books/list"
    get "books/new"
    match "books/create" => "books#create", :via => :post
    match "books/edit/:id" => "books#edit", :as => :edit_book, :via => :get
    match "books/update/:id" => "books#update", :as => :update_book, :via => :put
    match "books/destroy/:id" => "books#destroy", :as => :books_destroy, :via => :delete

    get "books/:book_id/sections/index" => "sections#index", :as => :book_sections
    get "books/:book_id/sections/new" => "sections#new", :as => :new_book_section
    get "books/:book_id/sections/show/:id" => "sections#show",:as => :show_book_section
    match "books/:book_id/sections/create" => "sections#create", :as => :create_book_section, :via => :post
    match "books/:book_id/sections/edit/:id" => "sections#edit", :as => :edit_book_section, :via => :get
    match "books/:book_id/sections/update/:id" => "sections#update", :as => :update_book_section, :via => :put
    match "books/:book_id/sections/destroy/:id" => "section#destroy", :as => :destroy_book_section, :via => :delete

  end
  

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :isbn, :download_link,:author, :book_coin, :name, :published, :published_at, :publisher, :contents, :cover, :attachment
  has_attached_file :cover, 
                    :url => "/books/:id/cover/:basename.:extension",
                    :path => ":rails_root/public/books/:id/cover/:basename.:extension" 

  has_attached_file :attachment, 
                    :url => "/books/:id/:basename.:extension",
                    :path => ":rails_root/public/books/:id/:basename.:extension" 
                    
  has_many :comments
  has_many :sections
end

app/controllers/admin/books_controller.rb
#-*- coding: utf-8 -*-
class Admin::BooksController < AdminController
  before_filter :authenticate_user!
  before_filter :set_curr_nav

  def list
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def show
  end

  def create
    @book = Book.new(params[:book])
    if @book.save
      redirect_to admin_books_list_url
    else
      render action: 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      redirect_to admin_books_list_url
    else
      render action: 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to admin_books_list_url, notice: "资源删除成功"
  end

  private
  def set_curr_nav
    @curr_nav = 'books'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	@books = Book.paginate(page: params[:page], per_page: 9)
  	@curr_nav = "books"
  end

  def show
  	@curr_nav = "books"
  	@book = Book.find(params[:id])
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/edit.html.erb
<div class="bs-example" id="category_res"> 
<div class="row app-list">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>编辑图书</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span><%= link_to "返回", admin_books_list_path, :class => 'navbar-link'%></span>
				</div>
			</div> 
			          
			<div class="row app-list">
			    <%= form_for(@book, :url => admin_update_book_path, method: :put, :html => {:class => "form-horizontal"}) do |f| %>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">名称</label>
						<div class="col-lg-10">
						<%= f.text_field :name, :autofocus => true,  :class => "form-control", :placeholder => "名称" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">作者</label>
						<div class="col-lg-10">
						<%= f.text_field :author, :class => "form-control", :placeholder => "作者" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">出版社</label>
						<div class="col-lg-10">
						<%= f.text_field :publisher, :class => "form-control", :placeholder => "出版社" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">出版时间</label>
						<div class="col-lg-10">
						<%= f.date_select :published_at, :include_blank => true%>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">下载链接</label>
						<div class="col-lg-10">
						<%= f.text_field :download_link, :class => "form-control", :placeholder => "下载链接" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">书币</label>
						<div class="col-lg-10">
						<%= f.text_field :book_coin, :class => "form-control", :placeholder => "书币" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">是否发布</label>
						<div class="col-lg-10">
						<%= f.text_field :published,  :class => "form-control", :placeholder => "出版时间" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">封面</label>
						<div class="col-lg-10">
						<%= f.file_field :cover, :class => "form-control" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">目录</label>
						<div class="col-lg-10">
						<%= f.text_area :contents, :class => "form-control" %>
						</div>
					</div>

					<div class="form-group">
						<label for="apk" class="col-lg-2 control-label">附件</label>
						<div class="col-lg-10">
							<%= f.file_field :attachment,  :class => "form-control" %>
							<%= f.submit "上传", :class => "btn btn-primary", :id => "upload_apk"%>
						</div>
					</div>	


				<% end %>
			</div> 
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>
</div>

app/views/admin/books/list.html.erb
<div class="bs-example" id="category_res"> 
<div class="row">
	<div class="col-lg-1"></div>
	<div class="col-lg-10">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>图书一览</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span class="pull-right"><%= link_to_icon "add", admin_books_new_path, :class => 'navbar-link'%></span>
				</div>
			</div> 

			<table class="table table-striped">
		        <thead>
		          <tr>
		            <th>序号</th>
		            <th>名称</th>
		            <th>出版时间</th>
		            <th>书币</th>
		            <th>发布</th>
		            <th></th>
		            <th></th>
		            <th></th>
		          </tr>
		        </thead>
		        <tbody>
		        <%@books.each_with_index do |book, index|%>
		         	<tr>
			            <td><%= index + 1%></td>
			            <td><%= book.name %></td>
			           	<td><%= book.published_at %></td>
						<td><%= book.book_coin %></td>
						<td><%= book.published %></td>
						<td><%= link_to "章节", admin_book_sections_path(book)%></td>
			            <td><%= link_to_icon "edit", admin_edit_book_path(book)%></td>
			            <td><%= link_to_icon "delete", admin_books_destroy_path(book), method: :delete, data: { confirm: '确定删除吗?' }%></td>
		          	</tr>
		        <%end%>
		        </tbody>
		    </table>
		</div>
	</div>
	<div class="col-lg-1"></div>
</div>
</div>

app/views/admin/books/new.html.erb
<div class="bs-example" id="category_res"> 
<div class="row app-list">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>添加图书</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span><%= link_to "返回", admin_books_list_path, :class => 'navbar-link'%></span>
				</div>
			</div> 
			          
			<div class="row app-list">
			    <%= form_for(@book, :url => admin_books_create_path, :html => {:class => "form-horizontal"}) do |f| %>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">名称</label>
						<div class="col-lg-10">
						<%= f.text_field :name, :autofocus => true,  :class => "form-control", :placeholder => "名称" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">作者</label>
						<div class="col-lg-10">
						<%= f.text_field :author, :class => "form-control", :placeholder => "作者" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">出版社</label>
						<div class="col-lg-10">
						<%= f.text_field :publisher, :class => "form-control", :placeholder => "出版社" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">出版时间</label>
						<div class="col-lg-10">
						<%= f.text_field :published_at, :class => "form-control", :placeholder => "出版时间" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">下载链接</label>
						<div class="col-lg-10">
						<%= f.text_field :download_link, :class => "form-control", :placeholder => "下载链接" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">书币</label>
						<div class="col-lg-10">
						<%= f.text_field :book_coin, :autofocus => true,  :class => "form-control", :placeholder => "书币" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">是否发布</label>
						<div class="col-lg-10">
						<%= f.text_field :published, :autofocus => true,  :class => "form-control", :placeholder => "出版时间" %>
						</div>
					</div>

					<div class="form-group">
						<label for="apk" class="col-lg-2 control-label">附件</label>
						<div class="col-lg-10">
							<%= f.file_field :attachment,  :class => "form-control" %>
							<%= f.submit "上传", :class => "btn btn-primary", :id => "upload_apk"%>
						</div>
					</div>	


				<% end %>
			</div> 
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>
</div>

app/views/admin/books/show.html.erb
<h1>Admin::Books#show</h1>
<p>Find me in app/views/admin/books/show.html.erb</p>