config/routes.rb
ConnotiveCartoon::Application.routes.draw do

  get "books/index"
  match "books/show/:id" => 'books#show', :as => :books_show, :via => :get
  get "/about", to: 'about#index'

  get "cartoons/:nav/page/:page", to: 'cartoons#index'
  
  match "cartoons/check/list" => "cartoons#check_list", :as => :check_cartoons, :via => :get
  match "cartoons/check/:id" => "cartoons#check", :as => :check_cartoon, :via => :get
  match "user/:username" => "user#show", :as => :show_user, :via => :get
  get "user/edit"
  get "user/update"

  post "comments/create"
  post "comments/add_book_comment"

  devise_for :users

  root :to => 'cartoons#index'
  get "cartoons/index"
  match "cartoons/:nav/show/:id" => "cartoons#show", :as => :show_cartoons, :via => :get
  match "cartoons/download/:id" => "cartoons#download", :as => :download_cartoon, :via => :get
  get "/download/apk", to: "cartoons#download_apk", :as => :download_apk

  namespace :admin do 
    get "system/index"
    get "system/show_upload_apk"
    post "system/upload_apk"
    get "system/edit_apk/:id", to: 'system#edit_apk', :as => :system_edit_apk
    put "system/update_apk/:id", to: 'system#update_apk', :as => :system_update_apk

    get "categories/list"
    get "categories/new"
    post "categories/create"
    get "categories/edit/:id", to: "categories#edit", :as => "categories_edit"
    put "categories/update/:id", to: "categories#update", :as => "categories_update"
    delete "categories/destroy/:id", to: "categories#destroy", :as => "categories_destroy"

    get "cartoons/index"
    get "cartoons/list"
    get "cartoons/new"
    get "cartoons/show"
    get "cartoons/create"
    get "cartoons/edit"
    get "cartoons/update"
    match "cartoons/destroy/:id" => "cartoons#destroy", :as => :destroy_cartoon, :via => :delete
    post "cartoons/import"
    post "cartoons/get_cartoons_list"

    get "scrap_sources/list"
    get "scrap_sources/new"
    match "scrap_sources/show/:id" => "scrap_sources#show", :as => :show_scrap_source, :via => :get
    match "scrap_sources/create" => "scrap_sources#create", :as => :create_scrap_source, :via => :post
    match "scrap_sources/edit/:id" => "scrap_sources#edit", :as => :edit_scrap_source, :via => :get
    match "scrap_sources/update/:id" => "scrap_sources#update", :as => :update_scrap_source, :via => :put
    match "scrap_sources/destroy/:id" => "scrap_sources#destroy", :as => :destroy_scrap_source, :via => :delete
  
    get "books/list"
    get "books/new"
    match "books/create" => "books#create", :via => :post
    match "books/edit/:id" => "books#edit", :as => :edit_book, :via => :get
    match "books/update/:id" => "books#update", :as => :update_book, :via => :put
    match "books/destroy/:id" => "books#destroy", :as => :books_destroy, :via => :delete

    get "books/:book_id/sections/index" => "sections#index", :as => :book_sections
    get "books/:book_id/sections/new" => "sections#new", :as => :new_book_section
    get "books/:book_id/sections/show/:id" => "sections#show",:as => :show_book_section
    match "books/:book_id/sections/create" => "sections#create", :as => :create_book_section, :via => :post
    match "books/:book_id/sections/edit/:id" => "sections#edit", :as => :edit_book_section, :via => :get
    match "books/:book_id/sections/update/:id" => "sections#update", :as => :update_book_section, :via => :put
    match "books/:book_id/sections/destroy/:id" => "section#destroy", :as => :destroy_book_section, :via => :delete

  end
  

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :book
  attr_accessible :content, :book_id, :section_number, :name
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < AdminController
  before_filter :authenticate_user!
  before_filter :set_curr_nav

  def index
    @book = Book.find(params[:book_id])
    @sections = @book.sections
  end

  def new
    @book = Book.find(params[:book_id])
    @section = Section.new
  end

  def show
    @section = Section.find(params[:id])
  end

  def create
    @section = Section.new(params[:section])
    if @section.save
      redirect_to admin_book_sections_url
    else
      render action: 'new'
    end
  end

  def edit
    @book = Book.find(params[:book_id])
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(params[:section])
      redirect_to admin_book_sections_url
    else
      render action: 'edit'
    end
  end

  def destroy
  end

  private
  def set_curr_nav
    @curr_nav = 'books'
  end
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/views/admin/sections/edit.html.erb
<div class="bs-example" id="category_res"> 
<div class="row app-list">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>编辑章节</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span><%= link_to "返回", admin_book_sections_path, :class => 'navbar-link'%></span>
				</div>
			</div> 
			          
			<div class="row app-list">
			    <%= form_for(@section, :url => admin_update_book_section_path, method: :put, :html => {:class => "form-horizontal"}) do |f| %>
			    	<%= hidden_field_tag "section[book_id]", @book.id%>
					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">章节号</label>
						<div class="col-lg-10">
						<%= f.text_field :section_number, :autofocus => true,  :class => "form-control", :placeholder => "章节号" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">名称</label>
						<div class="col-lg-10">
						<%= f.text_field :name, :class => "form-control", :placeholder => "名称" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">译文</label>
						<div class="col-lg-10">
							<%= f.text_area :content, :class => "form-control" %>
							<%= f.submit "添加译文", :class => "btn btn-primary", :id => "upload_apk"%>
						</div>
					</div>	


				<% end %>
			</div> 
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>
</div>

app/views/admin/sections/index.html.erb
<div class="bs-example" id="category_res"> 
<div class="row">
	<div class="col-lg-1"></div>
	<div class="col-lg-10">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div><%= @book.name%> 章节一览</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span class="pull-right"><%= link_to_icon "add", admin_new_book_section_path, :class => 'navbar-link'%></span>
				</div>
			</div> 

			<table class="table table-striped">
		        <thead>
		          <tr>
		            <th>章节号</th>
		            <th>名称</th>
		            <th></th>
		            <th></th>
		            <th></th>
		          </tr>
		        </thead>
		        <tbody>
		        <%@sections.each do |section|%>
		         	<tr>
			            <td><%= section.section_number %></td>
			            <td><%= section.name %></td>
						<td><%= link_to_icon "show", admin_show_book_section_path(@book.id, section)%></td>
			            <td><%= link_to_icon "edit", admin_edit_book_section_path(@book.id, section)%></td>
			            <td><%= link_to_icon "delete", admin_destroy_book_section_path(@book.id, section), method: :delete, data: { confirm: '确定删除吗?' }%></td>
		          	</tr>
		        <%end%>
		        </tbody>
		    </table>
		</div>
	</div>
	<div class="col-lg-1"></div>
</div>
</div>

app/views/admin/sections/new.html.erb
<div class="bs-example" id="category_res"> 
<div class="row app-list">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>添加章节</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span><%= link_to "返回", admin_book_sections_path, :class => 'navbar-link'%></span>
				</div>
			</div> 
			          
			<div class="row app-list">
			    <%= form_for(@section, :url => admin_create_book_section_path, :html => {:class => "form-horizontal"}) do |f| %>
			    	<%= hidden_field_tag "section[book_id]", @book.id%>
					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">章节号</label>
						<div class="col-lg-10">
						<%= f.text_field :section_number, :autofocus => true,  :class => "form-control", :placeholder => "章节号" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">名称</label>
						<div class="col-lg-10">
						<%= f.text_field :name, :class => "form-control", :placeholder => "名称" %>
						</div>
					</div>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">译文</label>
						<div class="col-lg-10">
							<%= f.text_area :content, :class => "form-control" %>
							<%= f.submit "添加译文", :class => "btn btn-primary", :id => "upload_apk"%>
						</div>
					</div>	


				<% end %>
			</div> 
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>
</div>

app/views/admin/sections/show.html.erb
<div class="bs-example" id="category_res"> 
<div class="row app-list">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>编辑图书</div>
			</div> 
			<%= raw @section.content%>
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>
</div>