config/routes.rb
ConnotiveCartoon::Application.routes.draw do

  get "books/index"
  match "books/show/:id" => 'books#show', :as => :books_show, :via => :get
  get "/about", to: 'about#index'

  get "cartoons/:nav/page/:page", to: 'cartoons#index'
  
  match "cartoons/check/list" => "cartoons#check_list", :as => :check_cartoons, :via => :get
  match "cartoons/check/:id" => "cartoons#check", :as => :check_cartoon, :via => :get
  match "user/:username" => "user#show", :as => :show_user, :via => :get
  get "user/edit"
  get "user/update"

  post "comments/create"
  post "comments/add_book_comment"

  devise_for :users

  root :to => 'cartoons#index'
  get "cartoons/index"
  match "cartoons/:nav/show/:id" => "cartoons#show", :as => :show_cartoons, :via => :get
  match "cartoons/download/:id" => "cartoons#download", :as => :download_cartoon, :via => :get
  get "/download/apk", to: "cartoons#download_apk", :as => :download_apk

  namespace :admin do 
    get "system/index"
    get "system/show_upload_apk"
    post "system/upload_apk"
    get "system/edit_apk/:id", to: 'system#edit_apk', :as => :system_edit_apk
    put "system/update_apk/:id", to: 'system#update_apk', :as => :system_update_apk

    get "categories/list"
    get "categories/new"
    post "categories/create"
    get "categories/edit/:id", to: "categories#edit", :as => "categories_edit"
    put "categories/update/:id", to: "categories#update", :as => "categories_update"
    delete "categories/destroy/:id", to: "categories#destroy", :as => "categories_destroy"

    get "cartoons/index"
    get "cartoons/list"
    get "cartoons/new"
    get "cartoons/show"
    get "cartoons/create"
    get "cartoons/edit"
    get "cartoons/update"
    match "cartoons/destroy/:id" => "cartoons#destroy", :as => :destroy_cartoon, :via => :delete
    post "cartoons/import"
    post "cartoons/get_cartoons_list"

    get "scrap_sources/list"
    get "scrap_sources/new"
    match "scrap_sources/show/:id" => "scrap_sources#show", :as => :show_scrap_source, :via => :get
    match "scrap_sources/create" => "scrap_sources#create", :as => :create_scrap_source, :via => :post
    match "scrap_sources/edit/:id" => "scrap_sources#edit", :as => :edit_scrap_source, :via => :get
    match "scrap_sources/update/:id" => "scrap_sources#update", :as => :update_scrap_source, :via => :put
    match "scrap_sources/destroy/:id" => "scrap_sources#destroy", :as => :destroy_scrap_source, :via => :delete
  
    get "books/list"
    get "books/new"
    match "books/create" => "books#create", :via => :post
    match "books/edit/:id" => "books#edit", :as => :edit_book, :via => :get
    match "books/update/:id" => "books#update", :as => :update_book, :via => :put
    match "books/destroy/:id" => "books#destroy", :as => :books_destroy, :via => :delete

    get "books/:book_id/sections/index" => "sections#index", :as => :book_sections
    get "books/:book_id/sections/new" => "sections#new", :as => :new_book_section
    get "books/:book_id/sections/show/:id" => "sections#show",:as => :show_book_section
    match "books/:book_id/sections/create" => "sections#create", :as => :create_book_section, :via => :post
    match "books/:book_id/sections/edit/:id" => "sections#edit", :as => :edit_book_section, :via => :get
    match "books/:book_id/sections/update/:id" => "sections#update", :as => :update_book_section, :via => :put
    match "books/:book_id/sections/destroy/:id" => "section#destroy", :as => :destroy_book_section, :via => :delete

  end
  

end

app/models/scrap_source.rb
class ScrapSource < ActiveRecord::Base
  attr_accessible :curr_page, :name, :src_url, :total_pages, :category_id
  belongs_to :category
  has_many :cartoons
end

app/controllers/admin/scrap_sources_controller.rb
#-*- coding: utf-8 -*-
class Admin::ScrapSourcesController < AdminController
  before_filter :authenticate_user!
  def list
    @scrap_sources = ScrapSource.all
  end

  def new
    @scrap_source = ScrapSource.new
  end

  def show
    @scrap_source = ScrapSource.find(params[:id])
  end

  def create
    @scrap_source = ScrapSource.new(params[:scrap_source])
    if @scrap_source.save
      redirect_to admin_scrap_sources_list_url, :notice => "创建抓取源成功"
    else  
      render action: 'new'
    end
  end

  def edit
    @scrap_source = ScrapSource.find(params[:id])
  end

  def update
    @scrap_source = ScrapSource.find(params[:id])
    if @scrap_source.update_attributes(params[:scrap_source])
      redirect_to admin_scrap_sources_list_url, :notice => "抓取源更新成功"
    else  
      render action: 'edit'
    end
  end

  def destroy
    @scrap_source = ScrapSource.find(:id)
    @scrap_source.destroy
    redirect_to admin_list_scrap_sources_url, notice: "资源删除成功"
  end
  
end

app/helpers/admin/scrap_sources_helper.rb
module Admin::ScrapSourcesHelper
end

app/views/admin/scrap_sources/create.html.erb
<h1>Admin::ScrapSources#create</h1>
<p>Find me in app/views/admin/scrap_sources/create.html.erb</p>

app/views/admin/scrap_sources/destroy.html.erb
<h1>Admin::ScrapSources#destroy</h1>
<p>Find me in app/views/admin/scrap_sources/destroy.html.erb</p>

app/views/admin/scrap_sources/edit.html.erb
<div class="row cartoon-list">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>编辑数据源</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span><%= link_to "返回", admin_scrap_sources_list_path, :class => 'navbar-link'%></span>
				</div>
			</div> 
			          
			<div class="row cartoon-list">
			    <%= form_for(@scrap_source, :url => admin_update_scrap_source_path(@scrap_source), method: :put, :html => {:class => "form-horizontal"}) do |f| %>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">名称</label>
						<div class="col-lg-10">
						<%= f.text_field :name, :autofocus => true,  :class => "form-control", :placeholder => "名称" %>
						</div>

						<label for="url" class="col-lg-2 control-label">地址</label>
						<div class="col-lg-10">
						<%= f.text_field :src_url, :class => "form-control", :placeholder => "地址" %>
						</div>

						<label for="url" class="col-lg-2 control-label">当前页码</label>
						<div class="col-lg-10">
						<%= f.text_field :curr_page, :class => "form-control", :placeholder => "当前页码" %>
						</div>

						<label for="url" class="col-lg-2 control-label">总页码</label>
						<div class="col-lg-10">
						<%= f.text_field :total_pages, :class => "form-control", :placeholder => "总页码" %>
						<%= f.submit "保存", :class => "btn btn-primary", :id => "update_source"%>
						</div>
					</div>	
				<% end %>
			</div> 
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>

app/views/admin/scrap_sources/list.html.erb
<div class="bs-example" id="cartoon_res"> 
  <div class="row">
    <div class="col-lg-1"></div><!--col-lg-9-->  
  	<div class="col-lg-10">
    	<div class="panel panel-rank">
          	<div class="panel-heading">漫画抓取资源</div> 
          	<div class="panel-action">
			    <div class="navbar">
					<span class="pull-right"><%= link_to_icon "add", admin_scrap_sources_new_path, :class => 'navbar-link'%></span>
				</div>
			</div> 
          	<table class="table table-striped">
		        <thead>
		          <tr>
		            <th>资源名</th>
		            <th>地址</th>
		            <th>当前页码</th>
		            <th>总页码</th>
		            <th></th>
		            <th></th>
		            <th></th>
		          </tr>
		        </thead>
		        <tbody>
		        <%@scrap_sources.each do |source|%>
		          <tr>
		            <td><%= source.name%></td>
		            <td><%= source.src_url%></td>
		            <td><%= source.curr_page%></td>
		            <td><%= source.total_pages%></td>
		            <td><%= link_to_icon 'show', '#'%></td>
		            <td><%= link_to_icon 'edit', admin_edit_scrap_source_path(source)%></td>
		            <td><%= link_to_icon "delete", admin_destroy_scrap_source_path(source), method: :delete, data: { confirm: '确定删除吗?' }%></td>
		          </tr>
		        <%end%>
		        </tbody>
		    </table>

        </div> <!--panel-->
    </div>
    <div class="col-lg-1"></div> 
  </div>
</div>

app/views/admin/scrap_sources/new.html.erb
<div class="row cartoon-list">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>添加数据源</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span><%= link_to "返回", admin_scrap_sources_list_path, :class => 'navbar-link'%></span>
				</div>
			</div> 
			          
			<div class="row cartoon-list">
			    <%= form_for(@scrap_source, :url => admin_create_scrap_source_path, :html => {:class => "form-horizontal"}) do |f| %>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">名称</label>
						<div class="col-lg-10">
						<%= f.text_field :name, :autofocus => true,  :class => "form-control", :placeholder => "名称" %>
						</div>

						<label for="url" class="col-lg-2 control-label">地址</label>
						<div class="col-lg-10">
						<%= f.text_field :src_url, :class => "form-control", :placeholder => "地址" %>
						</div>

						<label for="url" class="col-lg-2 control-label">当前页码</label>
						<div class="col-lg-10">
						<%= f.text_field :curr_page, :class => "form-control", :placeholder => "当前页码" %>
						</div>

						<label for="url" class="col-lg-2 control-label">总页码</label>
						<div class="col-lg-10">
						<%= f.text_field :total_pages, :class => "form-control", :placeholder => "总页码" %>
						<%= f.submit "添加", :class => "btn btn-primary", :id => "add_source"%>
						</div>
					</div>	
				<% end %>
			</div> 
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>

app/views/admin/scrap_sources/show.html.erb
<h1>Admin::ScrapSources#show</h1>
<p>Find me in app/views/admin/scrap_sources/show.html.erb</p>

app/views/admin/scrap_sources/update.html.erb
<h1>Admin::ScrapSources#update</h1>
<p>Find me in app/views/admin/scrap_sources/update.html.erb</p>