config/routes.rb
ConnotiveCartoon::Application.routes.draw do

  get "books/index"
  match "books/show/:id" => 'books#show', :as => :books_show, :via => :get
  get "/about", to: 'about#index'

  get "cartoons/:nav/page/:page", to: 'cartoons#index'
  
  match "cartoons/check/list" => "cartoons#check_list", :as => :check_cartoons, :via => :get
  match "cartoons/check/:id" => "cartoons#check", :as => :check_cartoon, :via => :get
  match "user/:username" => "user#show", :as => :show_user, :via => :get
  get "user/edit"
  get "user/update"

  post "comments/create"
  post "comments/add_book_comment"

  devise_for :users

  root :to => 'cartoons#index'
  get "cartoons/index"
  match "cartoons/:nav/show/:id" => "cartoons#show", :as => :show_cartoons, :via => :get
  match "cartoons/download/:id" => "cartoons#download", :as => :download_cartoon, :via => :get
  get "/download/apk", to: "cartoons#download_apk", :as => :download_apk

  namespace :admin do 
    get "system/index"
    get "system/show_upload_apk"
    post "system/upload_apk"
    get "system/edit_apk/:id", to: 'system#edit_apk', :as => :system_edit_apk
    put "system/update_apk/:id", to: 'system#update_apk', :as => :system_update_apk

    get "categories/list"
    get "categories/new"
    post "categories/create"
    get "categories/edit/:id", to: "categories#edit", :as => "categories_edit"
    put "categories/update/:id", to: "categories#update", :as => "categories_update"
    delete "categories/destroy/:id", to: "categories#destroy", :as => "categories_destroy"

    get "cartoons/index"
    get "cartoons/list"
    get "cartoons/new"
    get "cartoons/show"
    get "cartoons/create"
    get "cartoons/edit"
    get "cartoons/update"
    match "cartoons/destroy/:id" => "cartoons#destroy", :as => :destroy_cartoon, :via => :delete
    post "cartoons/import"
    post "cartoons/get_cartoons_list"

    get "scrap_sources/list"
    get "scrap_sources/new"
    match "scrap_sources/show/:id" => "scrap_sources#show", :as => :show_scrap_source, :via => :get
    match "scrap_sources/create" => "scrap_sources#create", :as => :create_scrap_source, :via => :post
    match "scrap_sources/edit/:id" => "scrap_sources#edit", :as => :edit_scrap_source, :via => :get
    match "scrap_sources/update/:id" => "scrap_sources#update", :as => :update_scrap_source, :via => :put
    match "scrap_sources/destroy/:id" => "scrap_sources#destroy", :as => :destroy_scrap_source, :via => :delete
  
    get "books/list"
    get "books/new"
    match "books/create" => "books#create", :via => :post
    match "books/edit/:id" => "books#edit", :as => :edit_book, :via => :get
    match "books/update/:id" => "books#update", :as => :update_book, :via => :put
    match "books/destroy/:id" => "books#destroy", :as => :books_destroy, :via => :delete

    get "books/:book_id/sections/index" => "sections#index", :as => :book_sections
    get "books/:book_id/sections/new" => "sections#new", :as => :new_book_section
    get "books/:book_id/sections/show/:id" => "sections#show",:as => :show_book_section
    match "books/:book_id/sections/create" => "sections#create", :as => :create_book_section, :via => :post
    match "books/:book_id/sections/edit/:id" => "sections#edit", :as => :edit_book_section, :via => :get
    match "books/:book_id/sections/update/:id" => "sections#update", :as => :update_book_section, :via => :put
    match "books/:book_id/sections/destroy/:id" => "section#destroy", :as => :destroy_book_section, :via => :delete

  end
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :scrap_sources
end

app/controllers/admin/categories_controller.rb
#-*- coding: utf-8 -*-
class Admin::CategoriesController < AdminController
  before_filter :authenticate_user!
  def list
    @curr_nav == "category"
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to admin_categories_list_url, :notice => "添加分类成功"
    else
      render action: 'new'
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes params[:category]
      redirect_to admin_categories_list_url, :notice => "编辑分类成功"
    else
      render action: 'edit'
    end
  end

  def destroy
    @category = Category.find params[:id]
    @category.destroy
    redirect_to admin_categories_list_url
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for(@category, :url => path, :html => {:class => "form-horizontal"}) do |f| %>
	<div class="form-group">
		<label for="name" class="col-lg-2 control-label">名称</label>
		<div class="col-lg-10">
		<%= f.text_field :name, :autofocus => true,  :class => "form-control", :placeholder => "名称" %>
		<%= f.submit "#{btn_text}", :class => "btn btn-primary", :id => "add_app"%>
		</div>
	</div>	
<% end %>

app/views/admin/categories/edit.html.erb
<div class="bs-example" id="category_res"> 
<div class="row app-list">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>编辑分类</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span><%= link_to "返回", admin_categories_list_path, :class => 'navbar-link'%></span>
				</div>
			</div> 
			          
			<div class="row app-list">
			    <%= form_for(@category, :url => admin_categories_update_path, method: :put, :html => {:class => "form-horizontal"}) do |f| %>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">名称</label>
						<div class="col-lg-10">
						<%= f.text_field :name, :autofocus => true,  :class => "form-control", :placeholder => "名称" %>
						<%= f.submit "保存", :class => "btn btn-primary", :id => "add_category"%>
						</div>
					</div>	
				<% end %>
			</div> 
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>
</div>

app/views/admin/categories/list.html.erb
<div class="bs-example" id="category_res"> 
<div class="row">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>分类一览</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span class="pull-right"><%= link_to_icon "add", admin_categories_new_path, :class => 'navbar-link'%></span>
				</div>
			</div> 

			<table class="table table-striped">
		        <thead>
		          <tr>
		            <th>序号</th>
		            <th>名称</th>
		            <th></th>
		            <th></th>
		          </tr>
		        </thead>
		        <tbody>
		         <%@categories.each_with_index do |category, index|%>
		         	<tr>
			            <td><%= index + 1%></td>
			            <td><%= category.name %></th>
			            <td><%= link_to_icon "edit", admin_categories_edit_path(category)%></th>
			            <td><%= link_to_icon "delete", admin_categories_destroy_path(category), method: :delete, data: { confirm: '确定删除吗?, 这将会删除相关联的漫画' }%></th>

		          	</tr>
		         <%end%>
		        </tbody>
		    </table>
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>
</div>

app/views/admin/categories/new.html.erb
<div class="bs-example" id="category_res"> 
<div class="row app-list">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<div class="panel panel-rank">
			<div class="panel-heading">
			    <div>添加分类</div>
			</div> 
			
			<div class="panel-action">
			    <div class="navbar">
					<span><%= link_to "返回", admin_categories_list_path, :class => 'navbar-link'%></span>
				</div>
			</div> 
			          
			<div class="row app-list">
			    <%= form_for(@category, :url => admin_categories_create_path, :html => {:class => "form-horizontal"}) do |f| %>

					<div class="form-group">
						<label for="name" class="col-lg-2 control-label">名称</label>
						<div class="col-lg-10">
						<%= f.text_field :name, :autofocus => true,  :class => "form-control", :placeholder => "名称" %>
						<%= f.submit "添加", :class => "btn btn-primary", :id => "add_category"%>
						</div>
					</div>	
				<% end %>
			</div> 
		</div>
	</div>
	<div class="col-lg-2"></div>
</div>
</div>

app/views/admin/categories/show.html.erb
<h1>Admin::Categories#show</h1>
<p>Find me in app/views/admin/categories/show.html.erb</p>